# Generated by Django 3.1 on 2020-08-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('userType', models.CharField(max_length=200)),
                ('scheduledInterviews', models.ManyToManyField(to='myportal.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myportal.slot')),
                ('participants', models.ManyToManyField(to='myportal.UserDetails')),
            ],
        ),
    ]
