# Generated by Django 3.1 on 2020-08-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdetails',
            name='participants',
        ),
        migrations.AddField(
            model_name='interviewdetails',
            name='participants',
            field=models.ManyToManyField(to='myportal.UserDetails'),
        ),
    ]
